### PR TITLE
fix(stm32CubeProg): fallback to BSD getopt on mac

### LINKED ISSUE #99: Cannot upload sketch on MacOS
**Describe the bug**
I am also not able to upload sketches from the Arduino IDE on MacOS. I have STM32cubeprog installed and working on my Mac but thats what I get from the Arduino IDE:

```
Sketch uses 110728 bytes (42%) of program storage space. Maximum is 262144 bytes.
Global variables use 8648 bytes (13%) of dynamic memory, leaving 56888 bytes for local variables. Maximum is 65536 bytes.
getopt: illegal option -- o
Terminating...
Failed uploading: uploading error: exit status 1
```

**To Reproduce**
No matter what upload method I select - SWD, UART, DFU the output is the same.
I am only able to upload the sketch by exporting compiled binary, open sketch folder in finder and move the .bin file to STLink drive.

**Expected behavior**
I expect to be able to flash STM32WL using Arduino IDE

**Desktop**
 - OS: Mac OS Sonoma 14.5
 - Arduino IDE version: 2.3.2
 - STM32 core version: 2.8.0
 - STM32 Low Power: 1.2.5
 - STM32 LoRaWAN: 0.2.0
 - Tools menu settings if not the default: Core logs enabled, Optimize: smallest, Runtime Newlib nano, UART: Enabled(generic serial), Board part number: Lora-E5 mini
 - Upload method: SWD
 
**Board (please complete the following information):**
 - Name: Seeed Wio-E5 Mini based on STM32wle5jc
 - Hardware Revision: v1.0

### PR DESCRIPTION
**Pull request by fpistm**
By default, MacOS uses getopt from FreeBSD and not the GNU-based one.
Then "-o" and long options are not supported except if gnu-getopt is installed.

Fixes #99

Main advantage to kept GNU getopt by default is it is able to deal with space in arguments.
Install the package `gnu-getopt` via e.g. [Homebrew](https://brew.sh):

```bash
brew install gnu-getopt
```
If not installed the BSD getopt is used but long option and space in arguments are not supported.

### CODE REVIEW

File: stm32CubeProg.sh [hunk 1]
```diff
@@ -53,11 +55,69 @@ aborting() {
...
+    ;;
+  Darwin*)
+    STM32CP_CLI=STM32_Programmer_CLI
+    if ! command -v $STM32CP_CLI >/dev/null 2>&1; then
+      export PATH="/Applications/STMicroelectronics/STM32Cube/STM32CubeProgrammer/STM32CubeProgrammer.app/Contents/MacOs/bin":"$PATH"
+    fi
+    if ! command -v $STM32CP_CLI >/dev/null 2>&1; then
+      aborting
+    fi
+    if ! command -v /usr/local/opt/gnu-getopt/bin/getopt >/dev/null 2>&1; then
```
Comment (lhvy) [inline stm32CubeProg.sh:80]: By the way, for Apple Silicon devices, the path should be `/opt/homebrew/opt/gnu-getopt/`, maybe this needs to be checked as well?

Comment (fpistm) [reply stm32CubeProg.sh:80]: Hi @lhvy 
Thanks for the feedback, I'm not familiar with mac.
So something like this:
```shell
    if ! command -v /usr/local/opt/gnu-getopt/bin/getopt >/dev/null 2>&1; then
      if ! command -v /opt/homebrew/opt/gnu-getopt/bin/getopt >/dev/null 2>&1; then
        echo "Warning: long options not supported due to getopt from FreeBSD usage."
        GNU_GETOPT=n
      else
        export PATH="/opt/homebrew/opt/gnu-getopt/bin":"$PATH"
      fi
    else
      export PATH="/usr/local/opt/gnu-getopt/bin":"$PATH"
    fi
```
